<?
$bdName="상품 판매 문의";
$bdGroup="";
$bdSkin="default";
$bdAlign="center";
$bdWidth="95%";
$bdStrlen="";
$bdPageNum="20";
$bdNew="";
$bdHot="";
$bdNoticeList="";
$bdLvlL="";
$bdLvlR="";
$bdLvlC="";
$bdLvlW="";
$bdLvlP="";
$bdIp="";
$bdIpAsterisk="";
$bdTypeView="0";
$bdUseLink="";
$bdUseFile="on";
$bdmaxsize_select="10485760";
$bdMaxSize="10485760";
$bdTypeMail="";
$bdHeader="<!-- 상단이미지 || 현재위치 -->
<TABLE width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">
<TR>
	<td class=\"path\">HOME > <b>상품 판매 문의</b></td>
</TR>
</TABLE>";
$bdFooter="";
$bdUseSubSpeech="";
$bdSubSpeechTitle="";
$bdSubSpeech="";
$bdUseComment="";
$bdSearchMode="0";
$bdField="";
$bdImg="";
$bdColor="";
$bdPrnType="1";
$bdListImgCntW="5";
$bdListImgCntH="4";
$bdListImgSizeW="100";
$bdListImgSizeH="100";
$bdListImg="";
$bdUserDsp="0";
$bdAdminDsp="0";
$bdSpamComment="3";
$bdSpamBoard="3";
$bdSecretChk="0";
$bdTitleCChk="on";
$bdTitleSChk="on";
$bdTitleBChk="";
$bdEmailNo="";
$bdEditorChk="1";
$bdHomepageNo="";
$bdUseXss="html";
$bdAllowPluginDomain="youtube.com|facebook.com|instagram.com|naver.com|daum.net|tistory.com|flicker.com";
$bdAllowPluginTag="iframe|embed";
$bdUseMobile="N";
?>